spring.application.name=api-service
spring.datasource.url=jdbc:mysql://mysql-persist:3306/cpd_bbdd
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.rabbitmq.host=rabbit
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest